### DISCUSSION TITLE
使用higress.io/auth-tls-secret配置客户端证书未生效

### DISCUSSION THREAD

**Discussion by ishells** [higress-group/higress#1004] [Q&A]
1、版本
     console 1.3.3 
     gateway 1.3.6
    controller 1.3.6
2、问题描述
    使用nginx ingress时，通过以下注解使用了自签的ca客户端证书（非域名ssl证书）+ https 验证客户端身份，客户端访问该域名时会验证客户端所安装的ca客户端证书
```
      ## 原 nginx 注解内容
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: 'true'
    nginx.ingress.kubernetes.io/auth-tls-secret: kube-system/ca-secret
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: '3'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'

    ## 完整nginx ingress yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: 'true'
    nginx.ingress.kubernetes.io/auth-tls-secret: kube-system/ca-secret
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: '3'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  name: xxx-gms-ing
  namespace: xxx-prod
spec:
  ingressClassName: xxx-nginx
  rules:
    - host: xxx.987ht.net
      http:
        paths:
          - backend:
              service:
                name: xxx-manage
                port:
                  number: 8808
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - xxx.987ht.net
      secretName: 987htnet-cert
```

    改用higress之后，按照文档指示，指定注解设置客户端ca证书，
    并额外设置域名ssl证书secret ( 客户端ca证书通过注解指定，域名ssl证书通过tls.secretName相关字段指定 ) 
    测试发现客户端证书并没有生效（不影响访问，未校验客户端已安装的同一CA证书），完整higress yaml如下：
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/auth-tls-secret: 987ca-cacert
    higress.io/destination: xxx-gameserver.xxx-test.svc.cluster.local:10000
    higress.io/ignore-path-case: 'false'
    higress.io/ssl-redirect: 'true'
  labels:
    higress.io/domain_xxx-game-higress.987ht.net: 'true'
    higress.io/resource-definer: higress
  name: xxx-game-higress
  namespace: higress-test
spec:
  ingressClassName: higress
  rules:
    - host: xxx-game-higress.987ht.net
      http:
        paths:
          - backend:
              resource:
                apiGroup: networking.higress.io
                kind: McpBridge
                name: default
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - xxx-game-higress.987ht.net
      secretName: 987ht-net-cert
```

问题描述如上，请求协助排查解决~谢谢
