### DISCUSSION TITLE
gateway api是否支持URLRewrite

### DISCUSSION THREAD

**Discussion by hoocoo** [higress-group/higress#1085] [Q&A]
如下配置注释掉filters可以访问到后端服务，但是放开注释则找不到路由
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: service-log-ht
  namespace: test
spec:
  parentRefs:
    - name: higress-gateway
      namespace: higress-system
  hostnames:
    - gateway-abc.cn
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/log-service/
#      filters:
#        - type: URLRewrite
#          urlRewrite:
#            path:
#              type: ReplacePrefixMatch
#              replacePrefixMatch: /
      backendRefs:
        - name: service-log-default
          port: 8000

**Comment by johnlanni** [comment]
2.0.0会支持，预计月底推出

**Reply by hoocoo** [reply]
好的，谢谢。

**Reply by hoocoo** [reply]
@johnlanni 大佬，请问下2.0.0支持了吗，我测试发现好像还有问题

**Reply by johnlanni** [reply]
@hoocoo 2.0.1你试了可以吗

**Reply by johnlanni** [reply]
@hanxiantao 帮忙确认下我们目前gateway api的版本支持这个 URLRewrite吗

**Reply by hoocoo** [reply]
![image](https://github.com/user-attachments/assets/d7c50c4a-cab7-4bf9-ad03-d2db545c9a7f)
![image](https://github.com/user-attachments/assets/590c3524-9052-4a6e-80d5-3b4ecacb4bc5)


```
  - backendRefs:
    - group: ""
      kind: Service
      name: energy-cloud-ocpi-default
      port: 8000
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replacePrefixMatch: /
          type: ReplacePrefixMatch
    matches:
    - path:
        type: PathPrefix
        value: /ocpi/

**Reply by hoocoo** [reply]
{
    "authority": "xxx.cn",
    "bytes_received": "0",
    "bytes_sent": "275",
    "downstream_local_address": "10.112.49.250:80",
    "downstream_remote_address": "10.112.18.19:34502",
    "duration": "65",
    "istio_policy_status": "-",
    "method": "GET",
    "path": "/ocpi/emsp/versions",
    "protocol": "HTTP/1.1",
    "request_id": "218bd7d6-804d-45a6-a786-249150467462",
    "requested_server_name": "-",
    "response_code": "404",
    "response_flags": "-",
    "route_name": "energy/autel-cloud-energy-gateway-ing",
    "start_time": "2024-10-15T01:46:42.089Z",
    "trace_id": "-",
    "upstream_cluster": "outbound|8000||energy-cloud-ocpi-default.energy.svc.cluster.local",
    "upstream_host": "10.112.51.238:8000",
    "upstream_local_address": "10.112.49.250:58334",
    "upstream_service_time": "65",
    "upstream_transport_failure_reason": "-",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "x_forwarded_for": "116.7.231.125,10.112.18.19",
    "response_code_details": "via_upstream"
}

**Comment by hanxiantao** [comment]
目前使用的 gateway-api 版本是 v0.8.0，是支持 URLRewrite 的

Istio 单元测试中的示例如下：

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: rewrite
  namespace: default
spec:
  parentRefs:
  - name: gateway
    namespace: higress-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /prefix-original
    name: prefix-path-rewrite
    filters:
    - type: URLRewrite
      urlRewrite:
        hostname: "new.example.com"
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: "/replacement"
    backendRefs:
    - name: httpbin
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /full-original
    name: full-path-rewrite
    filters:
    - type: URLRewrite
      urlRewrite:
        hostname: "new.example.com"
        path:
          type: ReplaceFullPath
          replaceFullPath: "/replacement"
    backendRefs:
    - name: httpbin
      port: 80
```

代码中也有对应的处理：

<img width="988" alt="image" src="https://github.com/user-attachments/assets/b03101a6-8eef-4dcc-8714-f898dfb2b2ea">

我这边后面本地 debug 调试下，也验证下这块功能

**Reply by hoocoo** [reply]
```
    - matches:
        - path:
            type: PathPrefix
            value: /api/common-service
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: energy-cloud-common-service-default
          port: 8000
```
```
    - matches:
        - path:
            type: PathPrefix
            value: /api/common-service/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: energy-cloud-common-service-default
          port: 8000
```
```
以上两个配置访问https://xxxl.com/api/common-service/ai/hello时，均会变成http://xxx.com//ai/hello，有两个//，当服务不兼容双斜杆时会报404
```
![image](https://github.com/user-attachments/assets/cafac23a-0e73-462b-aba6-1fceae011f43)
@johnlanni @hanxiantao
