### DISCUSSION TITLE
基于Higress访问大模型，无法传递apikey

### DISCUSSION THREAD

**Discussion by lixiaoyin-221** [higress-group/higress#1460] [Q&A]
使用docker： higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:latest 本地搭建 higress 环境
添加服务来源：DNS域名 | openai | api.openai.com | 443
添加路由：openai | 前缀匹配 ｜ /openai | openai.dns
添加域名和证书
路由开启AI代理：

```yaml
provider:
  apiTokens:
    - "sk-xx"
  modelMapping:
    '*': "gpt-4o-mini"
  type: "openai"
```

使用下面的请求进行访问

```bash
curl --location 'https://xxxhost:8643/openai/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
    "model": "gpt-4o-mini",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "Write a haiku that explains the concept of recursion."
        }
    ]
}'
```

提示未提供apikey，我换了一些模型，同样提示未能从header中获取到token。
首先我理解apikey应该是由网关插件接管，不再通过请求发送，再者我在header中传也同样不起作用，请问是哪里的问题
