### DISCUSSION TITLE
http转dubbo 失败

### DISCUSSION THREAD

**Discussion by gyy-bisontech** [higress-group/higress#1622] [Q&A]
我有dubbo 服务注册在nacos2上, 使用以下配置后, 发送请求并没有转发给dubbo服务, 而是会卡住, 过一段时间之后会超时, 配置如下
``` 
# cat nacos-secret.yml 
apiVersion: v1
data:
  nacosPassword: bmFjb3M=
  nacosUsername: bmFjb3M=
kind: Secret
metadata:
  name: higress-nacos-auth
  namespace: higress-system
type: Opaque

# cat mcpBridge.yml 
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: default
  namespace: higress-system
spec:
  registries:
  - domain: nacos-headless.dev
    nacosGroups:
    - {nacos_group}
    name: nacos-service-resource
    port: 8848
    type: nacos2
    authSecretName: higress-nacos-auth

# cat ingress.yml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: providers:com.channel.api.service.MyService:{dubbo_version}:{dubbo_group}.{nacos_group}.public.nacos
    higress.io/rpc-destination-name: httproute-http2rpc-demo
  name: httproute-http2rpc-demo-ingress
  namespace: higress-system
spec:
  ingressClassName: higress
  rules:
  - http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
        path: /dubbo
        pathType: Prefix

# cat toChannel.yml 
apiVersion: networking.higress.io/v1
kind: Http2Rpc
metadata:
  name: httproute-http2rpc-demo
  namespace: higress-system
spec:
  dubbo:
    service: com.channel.api.service.MyService
    version: {dubbo_version}
    group: {nacos_group}
    methods:
    - serviceMethod: confirm
      headersAttach: "*"
      httpMethods:
      - "POST"
      httpPath: "/dubbo/hello"
      paramFromEntireBody:
        paramType: "com.channel.api.request.MyServiceRequest"

```

这样配置之后表现出来的现象就是 curl请求不会调用到dubbo service, 会一致等待响应, 直到超时
