### DISCUSSION TITLE
MCP服务器如果代理的HTTP是SSE流式输出，是不是必须等待响应完成后才会进行协议转换输出给客户端？ || MCP server If the proxy HTTP is SSE streaming output, do you have to wait for the response to complete before performing a protocol conversion output to the client?

### DISCUSSION THREAD

**Discussion by xhguo80** [higress-group/higress#2329] [Q&A]
这是我的MCP服务器配置，目前现状是必须等待HTTP响应完成后才会进行协议转换输出给客户端。

```
responseTemplate:
  body: "{{ (index .choices 0).delta.content }}"
server:
  config:
    apiKey: "Bearer xxxxx"
  name: "rest-amap-server"
tools:
- args:
  - default: "Qwen/Qwen3-14B"
    description: "模型名称"
    name: "model"
    position: "body"
    required: true
    type: "string"
  - default: true
    description: "是否流式输出"
    name: "stream"
    position: "body"
    required: true
    type: "string"
  - description: "对话消息列表"
    items:
      description: "单条消息"
      properties:
        content:
          description: "消息文本内容"
          type: "string"
        role:
          default: "user"
          description: "消息角色,可选值:system|user|assistant"
          enum:
          - "system"
          - "user"
          - "assistant"
          type: "string"
      type: "object"
    name: "messages"
    position: "body"
    required: true
    type: "array"
  description: "智能问答"
  name: "chat"
  requestTemplate:
    argsToJsonBody: true
    headers:
    - key: "Authorization"
      value: "{{.config.apiKey}}"
    - key: "Content-Type"
      value: "application/json"
    method: "POST"
    url: "https://api.siliconflow.cn/v1/chat/completions"
    # 关键：SSE 流式支持
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600s"
```

---
This is my MCP server configuration. The current situation is that you must wait for the HTTP response to complete before the protocol conversion will be performed to the client.

```
responseTemplate:
  body: "{{ (index .choices 0).delta.content }}"
server:
  config:
    apiKey: "Bearer xxxxx"
  name: "rest-amap-server"
tools:
- args:
  - default: "Qwen/Qwen3-14B"
    description: "Model Name"
    name: "model"
    position: "body"
    required: true
    type: "string"
  - default: true
    description: "Whether stream output is output"
    name: "stream"
    position: "body"
    required: true
    type: "string"
  - description: "Conversation Message List"
    Items:
      description: "Single message"
      properties:
        content:
          description: "Message text content"
          type: "string"
        role:
          default: "user"
          description: "Message role, optional value: system|user|assistant"
          enum:
          - "system"
          - "user"
          - "assistant"
          type: "string"
      type: "object"
    name: "messages"
    position: "body"
    required: true
    type: "array"
  Description: "Smart Q&A"
  name: "chat"
  requestTemplate:
    argsToJsonBody: true
    headers:
    - key: "Authorization"
      value: "{{.config.apiKey}}"
    - key: "Content-Type"
      value: "application/json"
    method: "POST"
    url: "https://api.siliconflow.cn/v1/chat/completes"
    # Key: SSE streaming support
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600s"
```
