### DISCUSSION TITLE
认证透传 || Certified Transmission

### DISCUSSION THREAD

**Discussion by zcc19960910** [higress-group/higress#2361] [Q&A]
```yaml
server:
  name: "artifact"
  securitySchemes:
  - id: "backendApiKeyHeader"
    in: "header"
    name: "PRIVATE-TOKEN"
    type: "apiKey"
  - id: "ClientSideBearer"
    in: "query"
    name: "PRIVATE-TOKEN"
    type: "apiKey"
tools:
- description: "获取制品平台制品类型"
  name: "types"
  requestTemplate:
    method: "GET"
    security:
      id: "backendApiKeyHeader"
    url: "https://dev-gw.oceanbase-dev.com/obartifact/api/v1/projects/types"
  responseTemplate:
    body: "{\"result\": {{ .result | toJson }}"
  security:
    id: "ClientSideBearer"
    passthrough: true
```
    
上面的是我的MCP配置。
下面是我MCP服务地址。
http://我的ip:8080/user/sse?PRIVATE-TOKEN=123

后端API收到请求了，但是header里没有PRIVATE-TOKEN这个key。 意味着透传失败。 是我配置的有错误吗？

---
```yaml
server:
  name: "artifact"
  securitySchemes:
  - id: "backendApiKeyHeader"
    in: "header"
    name: "PRIVATE-TOKEN"
    type: "apiKey"
  - id: "ClientSideBearer"
    in: "query"
    name: "PRIVATE-TOKEN"
    type: "apiKey"
tools:
- description: "Get product platform product type"
  name: "types"
  requestTemplate:
    method: "GET"
    security:
      id: "backendApiKeyHeader"
    url: "https://dev-gw.oceanbase-dev.com/obartifact/api/v1/projects/types"
  responseTemplate:
    body: "{\"result\": {{ .result | toJson }}"
  security:
    id: "ClientSideBearer"
    passthrough: true
```
    
The above is my MCP configuration.
Below is my MCP service address.
http://My ip:8080/user/sse?PRIVATE-TOKEN=123

The backend API received the request, but the PRIVATE-TOKEN key is not included in the header. It means that the transmission failed. Is there any error in my configuration?
