### DISCUSSION TITLE
从nacos获取的mcp后端应该如何配置证书与协议 || How should the mcp backend obtained from Nacos configure certificates and protocols

### DISCUSSION THREAD

**Discussion by Xscaperrr** [higress-group/higress#2498] [Q&A]
对于higress自己配置的在此文档(https://higress.cn/docs/latest/ops/how-tos/https-upstream/?spm=36971b57.37829fe5.0.0.1c2c1052r7IKtz)中提供了配置证书的方法
但对于从nacos发现的mcp服务,仅有一个以下路由
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: higress-console.kube-system.svc.cluster.local:8080
    higress.io/enable-rewrite: "true"
    higress.io/rewrite-path: /landing
  generation: 1
  labels:
    higress.io/domain_higress-default-domain: "true"
    higress.io/resource-definer: higress
  name: default
  namespace: kube-system
spec:
  ingressClassName: higress
  rules:
  - http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
          servicePort: 0
        path: /
        pathType: Exact
  tls:
  - secretName: default

```
但nacos可以配置许多mcp后端,这些后端都会独立生成envoy中的cluster,有办法配置higress-gateway连接这些后端的证书吗？

---
For higress, you can configure the certificate in this document (https://higress.cn/docs/latest/ops/how-tos/https-upstream/?spm=36971b57.37829fe5.0.0.1c2c1052r7IKtz) configured by yourself, you provide a method to configure the certificate.
But for mcp services discovered from Nacos, there is only one of the following routes
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: higress-console.kube-system.svc.cluster.local:8080
    higress.io/enable-rewrite: "true"
    higress.io/rewrite-path: /landing
  Generation: 1
  labels:
    higress.io/domain_higress-default-domain: "true"
    higress.io/resource-defined: higress
  name: default
  namespace: kube-system
spec:
  ingressClassName: higress
  Rules:
  - http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
          servicePort: 0
        path: /
        pathType: Exact
  tls:
  - secretName: default

```
However, Nacos can configure many mcp backends, which will independently generate cluster in Envoy. Is there a way to configure the certificates for higress-gateway to connect these backends?
