### DISCUSSION TITLE
使用docker compose安装higress后跑“Higress 对接 Dubbo 服务”的demo(http2rpc)失败

### DISCUSSION THREAD

**Discussion by lcfang** [higress-group/higress#613] [Q&A] [answered]
1、使用`curl -fsSL https://higress.io/standalone/get-higress.sh | bash -s -- --use-builtin-nacos -p <你的密码>`安装higress
2、在higress-console中配置zk为服务来源：
![image](https://github.com/alibaba/higress/assets/30678878/7d11f91b-e87d-40e6-980d-92425d7f70fb)
3、启动dubbo-provider确保服务注册成功并能通过rpc正常被访问：
![image](https://github.com/alibaba/higress/assets/30678878/f7413aae-666a-410d-81c9-753909d60795)
![image](https://github.com/alibaba/higress/assets/30678878/7db53262-2bf4-4a5e-9de8-9a6b536c966a)
4、通过内置nacos配置ingress和http2rpc配置：
![image](https://github.com/alibaba/higress/assets/30678878/56296165-3639-42b2-a5a2-377d82f1377e)
![image](https://github.com/alibaba/higress/assets/30678878/235354d6-f097-4209-abb0-80598c55f524)
5、在ingress所在的服务器上通过http访问'curl "localhost/dubbo/hello?p=abc"'发现不通：
![image](https://github.com/alibaba/higress/assets/30678878/8c01ba78-b28d-4596-9794-ab305ea1ea43)

**Comment by CH3CHO** [comment]
Nacos配置的dataId点前面那一部分是对应CRD的复数形式，所以http2rpc应该用http2rpcs（这个没问题），ingress应该用ingresses（这个不对）。

**Reply by lcfang** [reply]
重新配置了，还是不行，但是报错变了，503错误：
![image](https://github.com/alibaba/higress/assets/30678878/27d9eb31-63ac-4cc7-8fb9-e189a3c52fc7)

**Reply by CH3CHO** [reply]
至少Ingress生效了。现在就是http2rpc的问题了。可以先看一下Gateway的日志，一个是有没有报错，另一个是accesslog可以贴一下，看看具体是什么错误。

也可以exec到gateway容器里，curl http://localhost:15000/config_dump，把配置内容贴上来

**Reply by CH3CHO** [reply]
503 很有可能是配置的服务名字有问题。建议核对一下。

**Reply by CH3CHO** [reply]
我本地测了一下，是可以的。

Ingress 配置：
![image](https://github.com/alibaba/higress/assets/2909796/29726bac-b4e5-4832-b857-f42251a07440)

Http2Rpc 配置：
![image](https://github.com/alibaba/higress/assets/2909796/ee1b6335-86aa-4d82-84e0-a267ee1412ac)

Dubbo 服务接口：
![image](https://github.com/alibaba/higress/assets/2909796/920367ed-c9a1-458c-98f1-113bd6ffdc0c)

Dubbo 服务实现：
![image](https://github.com/alibaba/higress/assets/2909796/1f02d622-1ab6-4261-a742-22429a563e62)

HTTP 请求测试：
![image](https://github.com/alibaba/higress/assets/2909796/1c07a7ab-cacd-4da5-b297-7eb752b5fe03)

**Reply by lcfang** [reply]
我看了一下，我的demo之前没有配置group和version，然后我的group写错了，version写了0.0.0，ingress中的higress.io/destination写的不对，所以访问失败了。
现在在demo里配置了group为dev和version为1.0.0，修改了ingress和http2rpc后访问，发现请求还是去找0.0.0版本的服务，导致访问失败：
![image](https://github.com/alibaba/higress/assets/30678878/f6b8645c-0151-472f-9acb-f8f02de16e96)
![image](https://github.com/alibaba/higress/assets/30678878/191884f6-7c92-48e0-a26d-70a80cc5ede7)
![image](https://github.com/alibaba/higress/assets/30678878/d3af6f22-8461-4f59-816f-bd0b019b1c74)
![image](https://github.com/alibaba/higress/assets/30678878/25858533-8023-41ee-8793-8bbe518876f0)
![image](https://github.com/alibaba/higress/assets/30678878/2e49713d-a246-42c7-bdd7-b16926326860)
我看了下config_dump里的配置，配置已经发布成功了：
![image](https://github.com/alibaba/higress/assets/30678878/1222eb05-1f17-4b3d-bcc7-2149a9dfce4f)
![image](https://github.com/alibaba/higress/assets/30678878/aed5d8b5-3e4e-49a9-a439-bd41eb409a80)
但是有一个servicemapping看起来没有更新成功：
![image](https://github.com/alibaba/higress/assets/30678878/ec57fb13-229d-46de-ab2d-385ec614cfb0)

**Reply by CH3CHO** [reply]
执行 `./bin/shutdown.sh && ./bin/startup.sh` 重启一下 Higress 试试看呢？

**Reply by lcfang** [reply]
这两个脚本是'higress-controller'里的吗？我进入容器没有看到啊
![image](https://github.com/alibaba/higress/assets/30678878/fb336a53-c3d9-4086-a130-ac2bc61e0204)
![image](https://github.com/alibaba/higress/assets/30678878/ba3a03c6-acea-4280-a547-78fca052aa6c)

**Reply by lcfang** [reply]
'docker restart'重启了一下higress，重新访问报'502 Bad Gateway'，查看'gateway'的config_dump里没有'services_mapping'这个配置了

**Reply by lcfang** [reply]
发现不能用`docker restart`重启higress，会导致higress不认识http2rpc：
![image](https://github.com/alibaba/higress/assets/30678878/ea6f68f8-a468-438d-927f-3700f342badb)

**Reply by lcfang** [reply]
重新执行了configure.sh和startup.sh，在console重新添加了zk源，在nacos里配置了ingress和http2rpc，controller不报不识别http2rpc的错误了，但是这个配置看起来还是没有生效。我在gateway里查看了config_dump，还是没有service_mapping的那个配置
![image](https://github.com/alibaba/higress/assets/30678878/975e059b-165c-4af3-8328-ff4b12fea5ae)

```
ingresses.httproute-http2rpc-demo-ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: providers:org.apache.dubbo.springboot.demo.DemoService:1.0.0:dev.zookeeper
    higress.io/rpc-destination-name: httproute-http2rpc-demo
  name: httproute-http2rpc-demo-ingress
  namespace: higress-system
spec:
  ingressClassName: higress
  rules:
  - http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
        path: /dubbo
        pathType: Prefix
        
http2rpcs.httproute-http2rpc-demo      
apiVersion: networking.higress.io/v1
kind: Http2Rpc
metadata:
  name: httproute-http2rpc-demo
  namespace: higress-system
spec:
  dubbo: 
    service: org.apache.dubbo.springboot.demo.DemoService
    version: 1.0.0
    group: dev
    methods: 
    - serviceMethod: sayHello
      headersAttach: "*"
      httpMethods: 
      - "GET"
      httpPath: "/dubbo/hello"
      params:
      - paramKey: p
        paramSource: QUERY
        paramType: "java.lang.String"
```
