### DISCUSSION TITLE
开启灰度发布后 访问不了，没有开启，可以通过访问后端服务，试了nginx和higress，都不行。求助

### DISCUSSION THREAD

**Discussion by wangmingbo123** [higress-group/higress#646] [Q&A]
采用的命令，无法访问

```
curl -H 'foo: bar'  -H 'Host: a.com' http://换成自己的ip/
```

对应的yaml文件：

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-demo
  labels:
    app: test-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-demo
  template:
    metadata:
      labels:
        app: test-demo
    spec:
      containers:
        - name: test-demo
          image: registry.cn-hangzhou.aliyuncs.com/wang-test-yu/test-demo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-demo
spec:
  selector:
    app: test-demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress-test-gray
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "foo"
    nginx.ingress.kubernetes.io/canary-by-header-value: "bar"

spec:
  ingressClassName: higress
  rules:
    - host: a.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-demo
                port:
                  number: 8080
```

去掉灰度注解，是可以访问的
```
curl   -H 'Host: a.com' http://换成自己的ip/
```

对应的yaml文件  

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress-test-gray
spec:
  ingressClassName: higress
  rules:
    - host: a.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-demo
                port:
                  number: 8080
```

其他的一些参考文档：试了没有效果
https://help.aliyun.com/zh/ack/ack-managed-and-ack-dedicated/user-guide/use-the-nginx-ingress-controller-for-canary-releases-and-blue-green-deployments?spm=a2c4g.11186623.0.0.94027cbeZmdhwl#section-e8q-t0s-dmi
