### DISCUSSION TITLE
测试gateway api 不成功

### DISCUSSION THREAD

**Discussion by alexzzh** [higress-group/higress#843] [Q&A] [answered]
按照 https://zhuanlan.zhihu.com/p/679799511 文档所述，测试higress gateway api资源效果:

-  gatewayclass.yaml
```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: higress-gateway
spec:
  controllerName: "higress.io/gateway-controller"
```
- gateway.yaml
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: higress-gateway
  namespace: higress-system
spec:
  gatewayClassName: higress-gateway
  listeners:
    - name: foobar
    hostname: "*.foobar.com"
    port: 22222
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
```
- httproute.yaml
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foobar
  namespace: default
spec:
  parentRefs:
  - name: higress-gateway
    namespace: higress-system
  hostnames: ["www.foobar.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /foo
    backendRefs:
    - name: foo-service
      port: 5678
```

- apply都是ok的
```
kubectl apply -f gatewayclass.yaml
gatewayclass.gateway.networking.k8s.io/higress-gateway created
kubectl  apply -f gateway.yaml
gateway.gateway.networking.k8s.io/higress-gateway created
kubectl apply -f httproute.yaml
httproute.gateway.networking.k8s.io/foobar created
```

- 查看higress-gateway监听的端口并没有 22222， 肯定访问不成功
```
hgctl gateway-config listener | grep  22222

$ curl http://192.168.49.2:22222/foo -H "Host: www.foobar.com"
curl: (7) Failed to connect to 192.168.49.2 port 22222: Connection refused
```

- 查看gateway资源状态，有点异常, 但不清楚怎么回事? 
```
$ kubectl describe  gateway higress-gateway  -n higress-system
Name:         higress-gateway
Namespace:    higress-system
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2024-02-27T08:01:03Z
  Generation:          1
  Resource Version:    97521
  UID:                 d9082788-1603-4488-8abe-8c361f11dd6b
Spec:
  Gateway Class Name:  higress-gateway
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  All
    Hostname:  *.foobar.com
    Name:      foobar
    Port:      22222
    Protocol:  HTTP
Status:
  Conditions:
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Pending
    Status:                Unknown
    Type:                  Accepted
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Pending
    Status:                Unknown
    Type:                  Programmed
    Last Transition Time:  2024-02-27T08:01:03Z
    Message:               failed to assign to any requested addresses: port 22222 not found for hostname "higress-gateway.higress-system.svc.cluster.local"
    Observed Generation:   1
    Reason:                AddressNotAssigned
    Status:                False
    Type:                  Ready
    Last Transition Time:  2024-02-27T08:01:03Z
    Message:               Resources not yet deployed to the cluster
    Observed Generation:   1
    Reason:                ResourcesPending
    Status:                False
    Type:                  Scheduled
  Listeners:
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2024-02-27T08:01:03Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                ListenerReady
      Status:                False
      Type:                  Conflicted
      Last Transition Time:  2024-02-27T08:01:03Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                ListenerReady
      Status:                False
      Type:                  Detached
      Last Transition Time:  2024-02-27T08:01:03Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                ListenerReady
      Status:                True
      Type:                  Ready
      Last Transition Time:  2024-02-27T08:01:03Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                ListenerReady
      Status:                True
      Type:                  ResolvedRefs
    Name:                    foobar
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
Events:       <none>

```

- use minikube and kubectl version
```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```
